import {qjs, qd} from './utility.js';

export const dom = {
  gameplay: qjs('gameplay'),
  start: qjs('start'),
  startOptions: qjs('start-options'),
  board: qjs('board'),
  debugLabelSvg: [],
  raptorSpaceGroup: qjs('raptor-space-group'),
  raptorSpace: [],
  humanSpace: [],
  humanEdge: {},
  trexSpace: [],
  humanPiece: [],
  raptorPiece: [],
  trexPiece: qd('trex-piece'),
  gameOver: qjs('game-over'),
  showMore: qjs('show-more'),
  dice: {},
  faces: {},
  editKill: [],
  selected: null,
  onSelected: null,
  move: null,
  path: [],
  variableImages: [],
};
