import {qr, qd} from './utility.js';

export const dom = {
  gameplay: qr('gameplay'),
  hud: qr('hud'),
  start: qr('start'),
  startOptions: qr('start-options'),
  board: qr('board'),
  debugLabelSvg: [],
  raptorSpaceGroup: qr('raptor-space-group'),
  raptorSpace: [],
  humanSpace: [],
  humanEdge: {},
  trexSpace: [],
  humanPiece: [],
  raptorPiece: [],
  trexPiece: qd('trex-piece'),
  gameOver: qr('game-over'),
  dice: {},
  faces: {},
  editKill: [],
  selected: null,
  onSelected: null,
  move: null,
  path: [],
  variableImages: [],
};
